#!/bin/bash

commitMessageFile=$1;
branch=$(git rev-parse --abbrev-ref HEAD);

if [[ "$branch" =~ ^((bugfix|feature|hotfix)[-/])?[A-Z0-9]+\-[0-9]+\- ]]; then
    issueKey=$(echo "$branch" | sed -r 's|((bugfix\|feature\|hotfix)[-/])?([A-Z0-9]+-[0-9]+).*|\3|g');
    echo -e "$issueKey $(cat $commitMessageFile)" > "$commitMessageFile";
fi;
